CHZZK-Study/Grass-Diary-Client

- grass-diary/package-lock.json
- grass-diary/package.json
- grass-diary/src/pages/Main/Main.jsx
| | axios | fetch |
|---|---|---|
|설치 필요 여부|써드파티 라이브러리로 설치 필요|현대 브라우저에 빌트인이라 설치 필요 없음|
|XSRF 보호|XSRF 보호를 제공함|별도 보호 없음|
|데이터 속성|data 속성을 사용|body 속성을 사용|
|데이터 형식|data는 object를 포함함|body는 문자열화 되어있음|
|성공 여부 판단|status가 200이고 statusText가 ‘OK’이면 성공|응답객체가 ok 속성을 포함하면 성공|
|JSON 변환|자동으로 JSON데이터 형식으로 변환| .json()메서드를 사용해야 함|
|요청 취소/타임아웃|요청을 취소할 수 있고 타임아웃을 걸 수 있음|해당 기능 존재하지 않음|
|HTTP 요청 가로채기|HTTP 요청을 가로챌 수 있음|기본적으로 제공하지 않음|
|다운로드 진행 지원|download진행에 대해 기본적인 지원을 함|지원하지 않음|
|브라우저 지원 범위|좀더 많은 브라우저에 지원됨|Chrome 42+, Firefox 39+, Edge 14+, and Safari 10.1+이상에 지원|
위 표를 보았을 때, axios는 별도의 설치가 필요하다는 단점이 있지만 그것을 커버할 만한 fetch보다 많은 기능 지원과 문법이 간소화되어 있다는 장점이 있습니다. 따라서, 간단하게 사용할 때는 fetch를, 확장성을 염두에 두고 있다면 axios를 사용하는 것이 좋습니다.
<br>
<br>
React
```javascript
const [date, setDate] = useState(null);
const [todayQuestion, …
```
> ✨ feat: Main 페이지 todayInfo API 연결

- grass-diary/src/pages/Intro/LoginModal/LoginModal.jsx
- 현재 사용자가 로그인 모달 내에 있는 구글 로그인 버튼을 클릭했을 때 구글 로그인 페이지로 이동하지 못하고 있습니다. 따라서 구글 간편 로그인 API 연결이 필요합니다.
> ✨ feat: 구글 간편 로그인 API 연동 (CLIENT-67)

- grass-diary/src/pages/Diary/Diary.jsx
- grass-diary/src/pages/Intro/LoginModal/LoginModal.jsx
- grass-diary/src/pages/Main/Main.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
- 현재 사용자가 회원가입/로그인을 완료한 후 메인 페이지로 이동했을 때, 로그인한 사용자의 데이터를 불러오지 못하고 있습니다. 따라서 사용자 고유 액세스 토큰을 인가받기 위해 요청 API의 헤더에 삽입해야 합니다.
> ✨ feat: 액세스 토큰 API 헤더에 삽입 (CLIENT-76)

- grass-diary/src/pages/Main/Main.jsx
현재 사용자가 로그인 시 메인 페이지로 redirect되는 과정에서 메인 페이지 URL에 담긴 액세스 토큰이 사라지지 않고 노출되고 있습니다. 따라서 정보 탈취를 방지하기 위해 URL에서 액세스 토큰을 숨기는 작업이 필요합니다.
> 페이지를 새로 고침 하지 않고도 브라우저의 주소 표시줄에 표시되는 URL을 변경할 수 있습니다.
> https://developer.mozilla.org/ko/docs/Web/API/History/pushState
- Local Storage에 사용자의 `AccessToken`을 저장한 뒤 메인 페이지의 URL로 변경시키고 있기 때문에, 로그인이 완료되고 메인 페이지로 redirect 되는 과정에서 아주 짧은 시간 동안 `AccessToken`이 노출되고 있습니다. 때문에 `Cookie` 사용 또는 `OAuth Authorization Code Flow` 등의 대안을 고려해 봐야 할 것 같습니다. 🏃
> 🔨 fix: 메인 페이지 URL에서 액세스 토큰 숨김

- grass-diary/src/components/ProtectedRoute.jsx
- grass-diary/src/pages/Main/Main.jsx
- grass-diary/src/router.jsx
- grass-diary/src/utils/checkAuth.js
- 현재 로그인을 완료하지 않은 사용자가 URL에 해당 페이지의 router를 추가하면, 로그인을 하지 않은 상태임에도 불구하고 해당 페이지로 이동 가능한 현상이 발생하고 있습니다. 따라서 페이지 접근 제한이 필요합니다.
> Outlet은 컴포넌트 내에 자식 라우트의 컴포넌트를 렌더링하는 자리 표시자 역할을 합니다. 즉, 부모 라우트 컴포넌트 안에서 Outlet을 배치하면, 해당 위치에 현재 URL에 해당하는 자식 라우트 컴포넌트가 렌더링됩니다. React Router v6 이상에서는 이 Outlet을 사용하여 중첩 라우팅을 구현합니다. Outlet은 공통적인 레이아웃을 유지하면서도 URL에 따라 다른 컨텐츠를 유연하게 표시할 수 있습니다.
> https://hsly22xk.tistory.com/405
> :sparkles: feat: 로그인 미완료 사용자의 페이지 접근 제한 추가

- grass-diary/src/pages/Main/Main.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
- grass-diary/src/services/index.js
- grass-diary/src/utils/authUtils.js
- 현재 로그인한 사용자의 AccessToken이 만료되어도 localStorage에서 삭제되지 않고 남아 있습니다. 따라서  만료된 토큰을 삭제하는 작업이 필요합니다.
- 현재 사용자의 잔디 현황 요청 API의 응답에서 `Internal Server Error (500)`이 발생하고 있어 임시 주석 처리를 해 둔 상태입니다. 🥺 (액세스 토큰을 삭제하는 조건이 `Internal Server Error (500)`이 발생한 경우이기 때문)
- 사용자가 로그인 시 메인 페이지로 한 번에 넘어가지 않고 인트로 페이지로 되돌아오는 현상이 발생해 localStorage 내의 `AccessToken` 존재 여부를 판단해 주는 `checkAuth()` 함수를 비동기로 변경한 뒤 적용해 주었습니다.
> :sparkles: feat: 액세스 토큰 만료 시 localStorage에 저장 중인 액세스 토큰 삭제

- grass-diary/src/pages/Intro/introComponents.jsx
- 현재 로그인을 완료한 사용자가 인트로 페이지에 접근했을 때, 로그인이 되어 있음에도 불구하고 일기 시작하기 버튼 클릭 시 회원가입 및 로그인 모달이 나타나고 있습니다. 따라서 로그인 상태에 따라 일기 시작하기 버튼의 동작을 변경해 주어야 합니다.
> :sparkles: feat: 로그인 상태에 따른 일기 시작하기 버튼 동작 변경

- grass-diary/src/components/ProtectedRoute.jsx
- grass-diary/src/hooks/useAuth.js
- 현재 로그인을 하지 않은 사용자가 /main 페이지를 제외한 다른 페이지에 접근했을 때, 제한되지 않고 이동이 가능합니다. 따라서 접근 제한 로직에 대한 수정이 필요합니다.
> 🔨 fix: 로그인 미완료 사용자의 페이지 접근 제한 버그 수정 (CLIENT-78)

- grass-diary/src/components/Like.jsx
- grass-diary/src/main.jsx
- grass-diary/src/pages/Diary/Diary.jsx
- grass-diary/src/pages/Diary/NonExistentDiary.jsx
- grass-diary/src/pages/Diary/modal/UnmodifyModal.jsx
- grass-diary/src/pages/Share/Share.jsx
- grass-diary/src/router.jsx
`api` /api/diary/{id}
-  작성자 이름
- 프로필 사진
- 제목( 날짜)
- 작성된 시간
- 비공개/공개 여부 
- 일기 내용
- 좋아요 개수 ( 0일 경우 보이지 않도록 설정)
- 삭제 된 후에 혹시라도 해당 페이지로 다시 렌더링 될 경우, `존재하지 않는 일기입니다` 알려주는 페이지로 이동.
- 프로필 사진
- 작성자 이름
- 일기 제목(작성된 날짜)
- 일기 내용( 350자가 넘어가면 ... 으로 처리)
- 좋아요 개수
`api` /api/shared/diaries/popular
이번주 기준 좋아요를 많이 받은 순으로 10개의 일기 불러오기 완료.
`api`  /api/shared/diaries/latest
최근 순으로 일기 불러오기 완료 
무한스크롤로 구현하는 방법은 2가지가 있습니다.
1. Scroll Event
Scroll 이벤트를 감지하여 api를 요청하는 방법.    
계속 감지해야하기 때문에 성능 저하 문제가 발생합니다 
→ `debounce` 나 `throttle` 를 적용해 개선 가능합니다. 
2. Intersection Observer Api 
브라우저의 뷰포트와 설정한 요소의 교차점을 관찰해 요소가 뷰포트에 포함되는지 아닌지 구별하는 기능을 제공합니다. 
**비동기적으로 실행**되기 때문에 scroll 이벤트 기반의 요소 관찰에서 발생하는 렌더링 성능이나 이벤트 연속 호출같은 문제 없이 사용할 수 있습니다.
'잔디 일기'에서는  `IntersectionObserver Api`를 사용하여 무한 스크롤을 구현했습니다.
데이터가 많지 않아 일기 3개 씩 불러오도록 …
> ✨ feat: 상세, 공유페이지 api 요청 및 무한스크롤 구현 

- grass-diary/src/hooks/useUser.js
- grass-diary/src/pages/Main/Main.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
- 현재 사용자의 고유 아이디를 조회 가능한 API를 사용하고 있지 않습니다. 많은 요청에서 사용 가능해야 하므로, 중복 가능성을 고려해 사용자의 고유 아이디를 조회할 수 있는 요청을 custom hook으로 구현해야 합니다.
> :sparkles: feat: 사용자 고유 아이디 조회 custom hook 구현 및 적용

- grass-diary/src/components/Header.jsx
- 현재 헤더 메뉴바 내에 있는 로그아웃 버튼을 클릭했을 때, 인트로 페이지로 이동하고 있지만 이에 대응하는 로그아웃 기능은 구현되어 있지 않습니다. 때문에 사용자가 서비스에서 로그아웃할 수 있도록 기능 구현이 필요합니다.
> :sparkles: feat: 사용자 로그아웃 구현

- grass-diary/src/components/Button.jsx
- grass-diary/src/components/Header.jsx
- grass-diary/src/components/Profile.jsx
- grass-diary/src/hooks/useProfile.js
- grass-diary/src/pages/Intro/introComponents.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
- grass-diary/src/pages/Setting/Setting.jsx
- grass-diary/src/pages/Setting/styles.js
- 현재 설정 페이지에서 닉네임 및 소개글을 수정해도, 모든 페이지에 수정 사항이 적용되고 있지 않습니다. 따라서 설정 페이지에서 사용자가 정보를 변경할 수 있도록 구현해야 합니다.
> :sparkles: feat: 설정 페이지 사용자 정보 수정 구현

- grass-diary/src/pages/MyPage/myComponents.jsx
- 현재 마이 페이지에 나타나는 일기를 클릭했을 때 상세 페이지가 나타나고 있지 않습니다. 따라서 일기 클릭 시 해당하는 일기의 상세 페이지로 이동할 수 있어야 합니다.
> :sparkles: feat: 일기 클릭 시 상세 일기 페이지로 이동

- grass-diary/src/pages/CreateDiary/CreateDiary.jsx
♻️ 작성 페이지 오늘의 기분
- moodValue :0 일 때 저장이 안되는 Axios Error 발생
- 0 값 무시 1-10으로 변경
->
:lipstick: 작성 페이지 오늘의 기분 수정
- moodValue range 비율이 안맞음 - UI 조정
- 0,10 값 무시 1-9로 변경
> :lipstick: reafactor: 작성 페이지 오늘의 기분 수정

- grass-diary/src/components/Ellipsis.jsx
- grass-diary/src/pages/Diary/Setting.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
- grass-diary/src/pages/MyPage/style.js
- 현재 사용자의 모든 일기가 최신 순으로만 정렬 가능하도록 구현되어 있습니다. 따라서 사용자가 정렬 순서를 선택할 수 있도록 추가적인 기능 구현이 필요합니다.
> :sparkles: feat: 마이 페이지 일기 날짜 순 정렬 구현 (CLIENT-65)

- grass-diary/src/pages/MyPage/myComponents.jsx
- grass-diary/src/pages/MyPage/style.js
- 현재 마이 페이지에 5개 이상의 일기가 작성되었을 시, 작성된 일기가 5개까지밖에 나타나지 않고 있습니다. 따라서 사용자가 작성한 일기를 모두 확인할 수 있도록 페이지 버튼 구현이 필요합니다.
> :sparkles: feat: 마이 페이지 일기 목록 페이지 버튼 구현 (CLIENT-98)

- grass-diary/package-lock.json
- grass-diary/package.json
- grass-diary/src/components/Feed.jsx
- grass-diary/src/pages/Diary/Diary.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
<br>
<br>
- Quill로 작성한 내용 전달에 HTML 태그가 적용되지 않고 그대로 노출
- HTML을 안전하게 렌더링하지 않고 텍스트로 처리
- 적용 되려면 HTML을 DOM에 직접 삽입
- 사용자가 입력한 HTML을 그대로 웹 페이지에 삽입하는 것은 XSS(Cross-Site Scripting)에 취약
- React의 dangerouslySetInnerHTML 속성을 사용하여 HTML문자열을 직접 DOM에 삽입
- dangerouslySetInnerHTML 사용할 때는 XSS를 방지하기 위해 sanitize(살균) 처리
- [dompurify 라이브러리 사용](https://meldu.tistory.com/25)
e.g.
```javascript
import DOMPurify from 'dompurify';
// 살균된 내용을 안전하게 렌더링하기 위한 함수
const createMarkup = (htmlContent) => {
return { __html: DOMPurify.sanitize(htmlContent) };
};
// 사용예시
<div dangerouslySetInnerHTML={createMarkup(diary.content)}/></div>
```
<br>
<br>
> :sparkles: feat: Quill 작성 내용 HTML 렌더링 적용

- grass-diary/src/components/Feed.jsx
- grass-diary/src/components/NormalLike.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
- grass-diary/src/pages/MyPage/style.js
- 마이페이지 및 공유페이지 피드에 적용해두었습니다. 
```
// import 후 
import NormalLike from './normalLike'; 
...
// 사용
<NormalLike likeCount={likeCount} justifyContent={'flex-end'} />
```
- likeCount를 주게 되면 하트 옆에 숫자 표기 가능
- justifyContent 값에 따라 왼쪽 정렬, 중앙정렬, 오른쪽 정렬 선택 가능. 
- justifyContent 값을 아예 주지 않으면 기본 왼쪽 정렬.
> ♻ refactor: 클릭 제한된 좋아요 컴포넌트 분리 및 적용

- grass-diary/src/hooks/useDiary.js
- grass-diary/src/hooks/ussGrass.js
- grass-diary/src/pages/MyPage/Diary.jsx
- grass-diary/src/pages/MyPage/Grass.jsx
- grass-diary/src/pages/MyPage/myComponents.jsx
- grass-diary/src/pages/MyPage/style.js
- grass-diary/src/utils/dateUtils.js
- 현재 마이 페이지의 UI만 임의적으로 구현된 상태입니다. 따라서 서버에서 데이터를 받아와 사용자의 잔디에 일부 정보를 담아 마이 페이지의 상단에 나타내야 합니다.
> :sparkles: feat: 마이페이지 잔디 구현 (CLIENT-61)

- grass-diary/src/services/index.js
- 현재 로그인한 사용자의 액세스 토큰이 만료되어도 자동으로 로그아웃되지 않고 있습니다. 따라서 Axios 응답 interceptor 관련 로직 변경이 필요합니다.
- Axios Interceptor는 React의 렌더링 사이클과 독립적으로 작동하기 때문에, 직접적으로 React 훅을 호출하는 것은 설계 원칙에 위반됩니다. 따라서 Interceptor 내부에서 직접 인증 상태를 관리하는 로직을 구현해야 합니다. (useLogout hook 삭제 후 직접 인증 상태 구현하는 방향으로 로직 변경)
> :hammer: fix: 액세스 토큰 만료 시 자동으로 로그아웃되지 않는 버그 수정

- grass-diary/package-lock.json
- grass-diary/package.json
- grass-diary/src/hooks/useDiary.js
- grass-diary/src/hooks/ussGrass.js
- grass-diary/src/main.jsx
- grass-diary/src/pages/CreateDiary/QuillEditor.jsx
- grass-diary/src/pages/MyPage/Diary.jsx
- grass-diary/src/pages/MyPage/Grass.jsx
- grass-diary/src/pages/Setting/Setting.jsx
> 아래 페이지 내 기능들에 `tanstack query` 적용
- 예기치 못한 문제 발생 예방을 위해 useEffect 내부에서 서버와 통신하던 방식에서, `tanstack query`를 적용해 변경해 주었습니다.
issue: #88
> ♻️ refactor: Tanstack Query 적용 (마이 페이지 및 설정 페이지)

- grass-diary/src/components/Feed/Feed.jsx
[React-quill 에서 작성한 데이터 렌더링 ( 태그 벗겨내기)](https://velog.io/@as13ljh/React-quill-%EC%97%90%EC%84%9C-%EC%9E%91%EC%84%B1%ED%95%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%A0%8C%EB%8D%94%EB%A7%81-%ED%83%9C%EA%B7%B8-%EB%B2%97%EA%B2%A8%EB%82%B4%EA%B8%B0)
issue: #91
> 🔨fix: Feed 컴포넌트, 일기 내용 html 태그 적용 문제 해결 

- grass-diary/package-lock.json
- grass-diary/package.json
- grass-diary/src/components/Container.tsx
- grass-diary/src/components/Header.tsx
- grass-diary/src/components/index.ts
- grass-diary/src/pages/CreateDiary/CreateDiary.tsx
- grass-diary/src/pages/Diary/Diary.tsx
- grass-diary/src/pages/Diary/NonExistentDiary.tsx
- grass-diary/src/pages/Intro/Intro.tsx
- grass-diary/src/pages/Intro/introComponents.tsx
- grass-diary/src/pages/Intro/styles.ts
- grass-diary/src/pages/Main/Main.tsx
- grass-diary/src/pages/MyPage/MyPage.tsx
- grass-diary/src/pages/MyPage/myComponents.tsx
- grass-diary/src/pages/MyPage/style.ts
- grass-diary/src/pages/Setting/Setting.tsx
- grass-diary/src/pages/Setting/styles.ts
- grass-diary/src/pages/Share/Share.tsx
- grass-diary/src/styles/reset.css
- grass-diary/src/types/module.d.ts
```css
// 추가
h1,
h2,
h3,
h4,
p {
margin: 0;
padding: 0;
}
// 변경
h1,
h2,
h3,
h4,
p,
button,
input,
label {
line-height: 1.34;
}
```
> ✨ feat: 소개 페이지 react-fullpage 적용

- grass-diary/src/pages/MyPage/Grass.tsx
**이슈 번호**: #111
**변경 유형**: [버그 수정]
- **변경 내용**:
해당 연도의 일 수(365/366)를 초과했을 경우에는 잔디가 생성되지 않도록 아래와 같은 조건문 추가 
```ts
if (!day) return;
```
**체크리스트**:
> :hammer: fix: 마이 페이지 연간 잔디 오류 수정

- grass-diary/src/components/Feed/PopularFeed.tsx
**이슈 번호**: #117 
**변경 유형**: [버그 수정]
- **변경 내용 1**:
PopularFeed( Top10 일기 )에 일기피드가 하나도 없을 때의 UI가 나오지 않아 수정. 
`이번 주는 공개된 일기가 아직 없어요` 문구가 뜨고 해당 구역의 height, lineheight 400px로 줄임. 
**체크리스트**:
> 🐛bug: PopularFeed 피드 없을 때 문구 뜨지 않는 버그 수정

- grass-diary/src/pages/Setting/Setting.tsx
- grass-diary/src/types/profile.ts
**이슈 번호**: #115 
**변경 유형**: [새로운 기능, 버그 수정]
- **변경 내용 1**:
필드 이름 변경으로 인해 기존 설정 페이지에서 닉네임 수정이 되지 않던 버그 수정
- **변경 내용 2**:
기존에는 설정 페이지에서 닉네임과 소개글을 변경할 경우, 닉네임과 소개글이 placeholder로 지정되어 있어 사용자가 일부만 수정하고 싶은 경우에도 전체를 수정해야 하는 불편함이 존재했음. 따라서 부분 수정이 가능하도록 기존 정보를 입력 필드에 바인딩함.
**체크리스트**:
> ✨ feat: 설정 페이지 닉네임 및 소개글 부분 수정 추가

- grass-diary/src/pages/Intro/LoginModal/LoginModal.tsx
- grass-diary/src/pages/Intro/introComponents.tsx
- grass-diary/src/types/modal.ts
**이슈 번호**: #119
**변경 유형**: [버그 수정]
- **변경 내용**:
로그인 모달 스타일 속성 중 `top` 속성을 props로 설정해 첫 번째 섹션과 마지막 섹션에서 모달 위치가 다르게 나타날 수 있도록 설정
**체크리스트**:
> :hammer: fix: 소개 페이지 로그인 모달 위치 수정

- grass-diary/src/pages/Diary/Diary.tsx
- grass-diary/src/pages/Diary/modal/ImageModal.tsx
- grass-diary/src/types/diary.ts
**이슈 번호**: #126 
**변경 유형**: [새로운 기능]
**변경 내용**:
이미지 파일을 업로드 했을 시 해당 일기 상세 페이지에서 이미지가 불러와지도록 구현
**체크리스트**:
- 이미지 파일 업로드는 `postman` 를 활용하여 데이터를 직접 POST 한 후 사용. 
- [백엔드 레포 PR 참고](https://github.com/CHZZK-Study/Grass-Diary-Server/pull/74) 
- 이미지 클릭 시
> ✨ feat: 상세페이지 이미지 불러오기 기능 구현

- grass-diary/src/components/Header.tsx
**이슈 번호**: #127 
**변경 유형**: [ 버그 수정]
로그인 유저만 확인할 수 있는 헤더의 메뉴바 및 프로필 사진이 로그아웃 시켜도 계속 남아있던 버그를 수정함.
로그아웃을 시켜도 쿼리가 전에 요청하여 받아두었던 memberId 데이터를 참조하기 때문에 문제가 발생하였음.
로그아웃 시 memberId 쿼리의 상태를 초기화하여 데이터를 초기 상태로 돌리기 위해 로그아웃 버튼 함수에 `resetQueries` 사용.
```tsx
// Header.tsx 
const queryClient = useQueryClient();
const handleLogout = () => {
clearAuth();
queryClient.resetQueries({ queryKey: ['memberId'] });
};
```
> 🔨fix: 로그아웃 시 헤더 메뉴바 사라지지 않는 오류 수정

- grass-diary/src/hooks/useDiary.ts
- grass-diary/src/pages/MyPage/Diary.tsx
- grass-diary/src/pages/MyPage/Grass.tsx
- grass-diary/src/pages/MyPage/myComponents.tsx
- grass-diary/src/pages/MyPage/style.ts
- grass-diary/src/styles/reset.css
**이슈 번호**: #125 
**변경 유형**: [새로운 기능]
- **변경 내용**: 
마이 페이지의 일기 목록 좌측에 사용자가 작성한 해시태그 목록을 표시하고, 해시태그를 클릭할 시 해당하는 해시태그가 포함된 일기만 필터링되어 나타나도록 구현
**체크리스트**:
- 현재 해시태그를 클릭했을 시 일기가 필터링되는 과정에서 데이터 로드 시간으로 인해 모든 일기가 우선적으로 나타난 뒤 일기가 필터링되는 현상이 발생하고 있습니다. (하단 이미지 참고) 해당 버그는 다른 작업부터 빠르게 마무리한 뒤 수정 진행하겠습니다!
- 사용자가 특정 해시태그를 작성한 게시글의 개수 표시
> ✨ feat: 마이 페이지 일기 해시태그 목록 구현

- grass-diary/src/pages/EditDiary/EditDiary.tsx
- grass-diary/src/router.tsx
EditDiary 컴포넌트를 생성해 본래 CreateDiary에서 수정기능을 분리했습니다.  
한 컴포넌트 내 여러 기능을 가지고 있으면 복잡성이 증가해 코드 이해가 어려워지고 기능 변경이 어려워집니다.
따라서 가독성, 유지보수를 위해 분리하였고 버그도 해결되었습니다. 
작성페이지 접근 오류가 발생했던 이유는 useParamsId의 diaryId 예외처리 부분 때문이었습니다. 
useParamsId는 url의 파라미터인 diaryId가 유효한 값인지 판단하고 숫자 타입으로 리턴합니다.
```tsx
export const useParamsId = () => {
const { diaryId } = useParams();
const diaryId_num = Number(diaryId);
const navigate = useNavigate();
useEffect(() => {
if (Number.isNaN(diaryId_num) || diaryId_num === 0) {
navigate('/non-existent-page');
}
}, [diaryId_num]);
return diaryId_num;
};
```
CreateDiary 컴포넌트에는 작성과 수정기능이 함께 들어있었습니다.
- 작성 시 주소창:  `/creatediary`
- 수정 시 주소창: `/editdiary/:diaryId`
그리고 이처럼 작성 기능일 때와 수정 기능일 때의 주소창은 형태가 다릅니다. 이 주소창을 기준으로 작성인지 수정인지 판단했습니다. 주소창 url의 파라미터에서 diaryId가 들어있다면 수정 페이지로 판단하여 수정 시의 코드가 …
> 🔨fix: 작성페이지 접근 불가 오류 수정

- grass-diary/src/components/Profile/Profile.tsx
- grass-diary/src/pages/MyPage/Diary.tsx
- grass-diary/src/pages/Setting/Setting.tsx
- grass-diary/src/recoil/profile/useProfile.ts
- grass-diary/src/types/profile.ts
- MyPage/Diary.tsx에 있는 TCreateMarpkup 타입 제거
TCreateMarpkup 가 types/diary.ts와 MyPage/Diary.tsx 2곳에 중복 선언되어 있어 MyPage/Diary.tsx에 있는 TCreateMarpkup을 제거했습니다. 
```ts
// Setting Page updateProfile Type 수정 전
interface IUpdateProfile {
nickname?: string;
profileIntro?: string;
}
//  수정 후 
type pickProfileImageURL = Pick<IProfile, 'profileImageURL'>;
// Setting Page updateProfile Type
type omitProfileImageURL = Omit<IProfile, 'profileImageURL'>;
```
- IUpdateProfile를 Omit 기능을 사용하여 omitProfileImageURL로 수정했습니다. 
- Pick 기능을 사용하여 profileImageURL만 선택한 pickProfileImageURL을 생성했습니다. 
- Partial 기능을 이용하고 있던 부분을 생성한 omit/pickProfileImageURL로 변경했습니다. 
- Partial 유틸리티 기능은 코드의 복잡성을 제거해주고 객체의 타입을 유연하게 만든다는 장점이 있습니다. Pick/Omit 기능을 이용하면 타입의 명확성이 높아지고 코드의 의도 파악이 쉽다는 장점이 있습니다. 사실 어떤걸 써도 상관없을 것 같다 생각하지만 프로필만 업데이트하는 …
> ♻ refactor: IProfile 타입 정리

- grass-diary/src/components/Feed/PopularFeed.tsx
- grass-diary/src/hooks/api/useDiaryDetail.ts
- grass-diary/src/hooks/api/usePatchDiary.ts
- grass-diary/src/hooks/api/useTodayDate.ts
- grass-diary/src/pages/CreateDiary/CreateDiary.tsx
- grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
- grass-diary/src/pages/DiaryDetail/Setting.tsx
- grass-diary/src/pages/EditDiary/EditDiary.tsx
- grass-diary/src/pages/Main/TopSection.tsx
- grass-diary/src/types/diary.ts
- grass-diary/src/types/today.ts
일기 수정 PATCH `/api/diary/{diaryId}` api를 axios에서  useMutation을 활용한 Tanstack query로 변경하였습니다.  
```ts
export const usePatchDiary = ({ diaryId, file, requestDto }: PatchDiaryProps) => {
... 
return useMutation({
mutationFn: () => fetchAxios({ diaryId, formData }),
onSuccess() {
navigate(`/diary/${diaryId}`, { replace: true, state: 'editcomplete' });
},
onError(error) {
console.error(error.message);
},
});
};
```
usePatchDiary 훅은 수정할 일기의 diaryId, 이미지 파일, requestDto를 인수로 받습니다. 
이 훅을 사용할 땐 아래처럼 mutate 함수를 사용해야합니다. 
```ts
const { mutate } = usePatchDiary({ diaryId, file, requestDto });
```
mutate 함수는 일기 수정이 끝난 후 저장버튼을 눌렀을 때 실행되도록 했습니다. 그리고 mutate 함수를 통해 mutationFn의 fetchAxios가 실행되며 수정된 일기가 서버로 전송됩니다.
onSuccess는 patch가 성공적으로 완료되었을 때 실행됩니다. 일기 수정이 성공적으로 끝나면 수정된 일기 상세 페이지로 이동하도록 했습니다. 
onError는 …
> ♻ refactor: EditDiary 페이지 Tanstack query 적용 및 localStroage의 lastWritingDate 사라짐 현상 해결

- grass-diary/src/components/Like/Like.tsx
- grass-diary/src/pages/CreateDiary/CreateDiary.tsx
- grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
- grass-diary/src/types/diary.ts
- CreateDiary 페이지의 useUser 경로 때문에 발생한 버그입니다. 해당 코드 삭제 후 다시 import  해주어 해결했습니다.   
- 좋아요 필드명 수정 `likedByLogInMember` -> `isLikedByLogInMember` 
- 닉네임 필드명 수정 `nickName` -> `nickname`
추가적인 참고 사항이나 관련된 문서, 링크 등을 제공해주세요.
변경 사항에 대한 스크린샷이 있다면 첨부해주세요.
**이슈 번호**: Close #170
> 🔨 fix: 일기 상세페이지 버그 해결

- grass-diary/src/pages/CreateDiary/CreateDiary.tsx
- grass-diary/src/pages/CreateDiary/QuillEditor.tsx
1️⃣ 작성 글을 임시 저장할 때 로컬 스토리지에 diary_info와 같이 image 값을 저장해 줍니다.
<br>
2️⃣ 기존에 `ImageHandler`함수에서 저장되는 변환된 base64 인코딩 값을 `onImageBase64Change`에 담아서 `CreateDiary` 컴포넌트에 보내줍니다
<br>
```ts
// QuillEditor
const reader = new FileReader();
reader.readAsDataURL(file);
reader.onloadend = () => {
const base64String = reader.result as string;
setImage({
imageId: 0,
imageURL: base64String,
});
onImageBase64Change(base64String);
```
```ts
// CreateDiary
const [imageBase64, setImageBase64] = useState<string | null>(null);
const handleImageBase64Change = (base64String: string) => {
setImageBase64(base64String);
};
```
<br>
🚀 작성 페이지에서 임시 저장을 실행할 때 `diary_draft`에 `dirayInfo`와 같이 변환된 이미지 값 `imageBase64`, 이미지 정보 `imageInfo`를 저장 합니다.
```ts
// CreateDiray
const handleSaveDraft = () => {
if (isContentEmpty) return; …
```
> ✨ feat: 작성 페이지 이미지 임시 저장 구현

- grass-diary/src/components/Notification/Callout.tsx
- grass-diary/src/pages/CreateDiary/CreateDiary.tsx
- grass-diary/src/styles/CreateDiary/CreateDiary.style.tsx
- grass-diary/src/styles/component/Notification/Callout.style.tsx
<br>
label 요소를 부모 박스(DailyQuestionBox, CustomEntryBox)에 하나 더 추가하여 박스 전체를 클릭하면 라디오 버튼이 체크되도록 처리.
<br>
<br>
svg 컴포넌트에 flex-shrink를 사용하여 고정된 영역을 가지도록 처리
콜아웃 컴포넌트도 같이 수정
<br>
추가적인 참고 사항이나 관련된 문서, 링크 등을 제공해주세요.
변경 사항에 대한 스크린샷이 있다면 첨부해주세요.
**이슈 번호**: #[이슈 번호]
> 🐛 fix: 릴리즈 이후 버그 및 개선사항 적용

- grass-diary/package-lock.json
- grass-diary/package.json
- grass-diary/src/components/Layout/Header.tsx
- grass-diary/src/hooks/useLogout.ts
- grass-diary/src/state/auth/authStore.ts
- grass-diary/src/state/auth/useAuth.ts
- grass-diary/src/state/auth/useExpDate.ts
- grass-diary/src/state/modal/useModal.ts
- grass-diary/src/state/user/useUser.ts
기존 코드는 memberId를 가져오는 useQuery를 5초마다 호출해서 로그인이 만료되었는지 확인했었습니다. 
setInterval 함수로 로그인 만료 타이머를 구현해 불필요한 api 요청을 줄이면서 로그인이 만료되었는지 확인하도록 변경했습니다. 
- `expDate`: 로그인 만료 시각 저장
- `setExpDate`: expDate 업데이트 함수
```ts
const useExpDate = () => {
const accessToken = localStorage.getItem('accessToken');
const { setExpDate } = useAuthActions();
const handleExpDate = () => {
if (accessToken) {
try {
const decode = jwtDecode(accessToken);
if (!decode.exp) return;
const date = new Date(0);
date.setUTCSeconds(decode.exp);
setExpDate(date);
} catch (error) {
console.error('Failed to decode token:', error);
}
}
};
return { handleExpDate };
};
```
- `handleExpDate`함수는 로그인이 만료되는 시각을 구해 expDate 상태를 업데이트합니다.
- 엑세스 토큰을 디코딩하면 만료 시각을 구할 수 있습니다. 
- 엑세스 토큰을 반환하는데 `jwt-decode` 라이브러리를 사용합니다. 
참고: [쉽게 이해하는 jwt-decode …
> 🔨 fix: 로그인 만료 로직 변경 
